services:
  kspeeder:
    build:
      context: .
      dockerfile: Dockerfile.architecture
    container_name: kspeeder
    ports:
      - "5443:5443"
      - "5003:5003"
    volumes:
      - ./kspeeder-data:/kspeeder-data
      - ./kspeeder-config:/kspeeder-config
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - KSPEEDER_PORT=5443
      - KSPEEDER_ADMIN_PORT=5003
      - KSPEEDER_CONFIG=/kspeeder-config
      - KSPEEDER_DATA=/kspeeder-data
      - KS_USER_NODES_CONFIG=/kspeeder-config/nodes.yaml
